[project]
source_dir = "/path/to/src/dir"                   # source code dir
target_dir = "/"                                  # path in the ROM, normally "/"
ignore-pattern = [
    "**/__pycache__",                             # python cache files
    "**/.*",                                      # hidden files
    "**/*.gba",                                   # gba files
    "**/*.sav",                                   # sav files
    "**/*.sgm",                                   # sgm files
]

[mpy-cross]
compile = true                                    # compile code with mpy-cross
path = "/run/media/dreagonmon/Data/Code/Python/gba_mpy_tools/.venv/bin/mpy-cross"
params = "-O2 -X emit=bytecode"                   # params passed to mpy-cross
ignore-pattern = [
    "boot.py",                                    # keep entry file as .py
    "main.py",                                    # keep entry file as .py
]

[gba]
template = "/path/to/template/micropython.gba"    # the micropython.gba template ROM
output = "/path/to/output/game_name.gba"          # the output ROM
emulator = "mgba-qt"                              # mgba emulator
params = "-l 255"                                 # params passed to mgba
